### ISSUE TITLE
Update preset for CRA

### ISSUE THREAD

**Issue by mrmckeb** [storybookjs/presets#36]
## Preparing CRA preset for release

The preset for CRA has been around for a while now, and is getting a few hundred downloads a week with no reported issues.

It's time to polish up the preset, and remove the in-built preset from CRA.

The PR in-progress is:
https://github.com/storybookjs/presets/pull/29

### TODO:
- [x] Add support for custom Babel configs.
- [x] Handle environment variables prefixed with CRA (see: https://github.com/storybookjs/storybook/issues/4841)
- [x] Change the README title (embarrassing).
- [x] Add basic automation tests.
- [x] Add and document support for `react-docgen-typescript-loader`. Covers #21.
- [x] Create a PR for `@storybook/react` to remove built-in preset.
  - [x] This preset should be used instead of the existing functionality.
  - [x] On `init`, this preset should be installed if the app matches the criteria.
  - [x] Document migration steps and update docs for React and TypeScript.
    - Look through all React/TypeScript docs.
    - https://github.com/storybookjs/storybook/blob/a65bd69bbe0e5dff716f8295785ac4fd60214d4e/docs/src/pages/guides/guide-react/index.md#automatic-setup
  - [x] See if we can solve https://github.com/storybookjs/storybook/issues/8201.
  - [x] Remove any other potential conflicting packages.

### Future tasks:
- [ ] Add better automation tests, covering:
  - [ ] https://github.com/storybookjs/storybook/issues/6479
